### PR TITLE
Implement tessellation for large border radii.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves performance on the Moiré demo.

### CODE REVIEW

**Comment by pcwalton** [comment]
I ended up not using the fancy algorithms I was coming up with, because (a) this trivial one works just as well, and (b) the fact that it tessellates into rectangles and the fact that boundaries of the rectangles can be easily computed individually end up being really useful properties.

**Comment by glennw** [comment]
This looks good to me - could you just confirm that it still gets the triangle border corners correct for the acid2 ref test?

**Comment by pcwalton** [comment]
Ah, this indeed broke the borders (in multiple places in fact!) I'll fix it up tomorrow.

**Comment by pcwalton** [comment]
@glennw New PR fixes Acid2.

**Comment by glennw** [comment]
Thanks!

**Pull request merged**
